version: '3.8'

services:
  backend:
    build: .
    container_name: go-backend
    ports:
      - "3030:3030"
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server
    container_name: mongodbquizapp
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
